# Generated by Django 4.0.5 on 2022-08-28 10:27

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('detail', froala_editor.fields.FroalaField()),
                ('img', models.ImageField(null=True, upload_to='events/')),
            ],
            options={
                'verbose_name_plural': 'Event gallery',
            },
        ),
        migrations.CreateModel(
            name='EventsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=150)),
                ('img', models.ImageField(null=True, upload_to='event_imgs/')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.events')),
            ],
            options={
                'verbose_name_plural': 'Event Images',
            },
        ),
    ]
