# Generated by Django 4.0.5 on 2022-08-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_events_eventsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsimage',
            name='event',
        ),
        migrations.AddField(
            model_name='eventsimage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
