# Generated by Django 4.0.5 on 2022-09-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_eventsimage_event_eventsimage_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
