# Generated by Django 4.0.5 on 2022-09-01 16:15

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='detail',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
