# Generated by Django 4.0.5 on 2022-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='img',
            field=models.ImageField(null=True, upload_to='list_imgs/'),
        ),
    ]
