# Generated by Django 4.0.5 on 2022-08-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_list_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='img',
            field=models.ImageField(null=True, upload_to='categories_imgs/'),
        ),
    ]
