# Generated by Django 4.0.5 on 2022-08-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_categories_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
